# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BulkMp3Edit < Formula
  desc "Edit MP3 file's metadata in a bulk manner."
  homepage "https://github.com/seehait-c/bulk-mp3-edit"
  version "0.0.1"
  license "MIT"

  on_macos do
    url "https://github.com/seehait-c/bulk-mp3-edit/releases/download/0.0.1/bulk-mp3-edit_0.0.1_Darwin_all.tar.gz"
    sha256 "51c649c65c01c409ae8e002288453739a6c7a0de2a3191aa2b13af3c759f373c"

    def install
      bin.install "bulk-mp3-edit"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/seehait-c/bulk-mp3-edit/releases/download/0.0.1/bulk-mp3-edit_0.0.1_Linux_arm64.tar.gz"
      sha256 "419440e80d73c5eb55713a78b4fe8ba4fc660e1e862e2fc5ebfe0c5d8f0e8b6a"

      def install
        bin.install "bulk-mp3-edit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/seehait-c/bulk-mp3-edit/releases/download/0.0.1/bulk-mp3-edit_0.0.1_Linux_x86_64.tar.gz"
      sha256 "30397386e3e526cac8e2eec5b914b7c2b62b3a6ae44967dca8b9f7ec48e8f687"

      def install
        bin.install "bulk-mp3-edit"
      end
    end
  end
end
